SCUMM: Fix missing return values in HE games
Fixes missing return expressions from some scripts,
and the matching assignment of the return value on caller

for example
```
Script# 2136
[0000] (43) localvar1 = ((var281 + var284) / 1000)
[000E] (43) localvar2 = ((var283 + var286) / 1000)
[001C] (BD) stopObjectCode()
[0035] (66) stopObjectCodeB()
END
```

becomes
```
Script# 2136
[0000] (43) localvar1 = ((var281 + var284) / 1000)
[000E] (43) localvar2 = ((var283 + var286) / 1000)
[001C] (BD) return(getDistanceBetweenPoints.case28(array266[localvar0][0],array266[localvar0][2],localvar1,localvar2))
[0035] (66) stopObjectCodeB()
END
```
which reveals much more information.

and caller:
```
Script# 2148
[0000] (5D) if (localvar1 < ((localvar2 + localvar3) + 12)) {
[0011] (5D)   if (var462 == 2) {
[001A] (43)     localvar6 = 100
[001F] (73)   } else {
[0022] (43)     localvar6 = 200
[0027] (**)   }
[0027] (BF)   startScriptQuick2(2066,[roomarray3[(localvar0 - 37)]])
ERROR: No items on stack to pop!
[003A] (5D)   if (**** INVALID DATA **** < getRandomNumber(localvar6)) {
[003E] (BF)     startScriptQuick2(2136,[localvar0])
ERROR: No items on stack to pop!
[0047] (43)     localvar5 = **** INVALID DATA ****
[004A] (5D)     if (localvar5 > ((localvar1 + localvar3) + 12)) {
[005B] (BD)       stopObjectCode()
[005E] (**)     }
[005E] (**)   }
[005E] (**) }
[005E] (BD) stopObjectCode()
[0062] (66) stopObjectCodeB()
END
```
becomes:
```Script# 2148
[0000] (5D) if (localvar1 < ((localvar2 + localvar3) + 12)) {
[0011] (5D)   if (var462 == 2) {
[001A] (43)     localvar6 = 100
[001F] (73)   } else {
[0022] (43)     localvar6 = 200
[0027] (**)   }
[0027] (5D)   if (getRandomNumber(localvar6) < startScriptQuick2(2066,[roomarray3[(localvar0 - 37)]])) {
[003E] (43)     localvar5 = startScriptQuick2(2136,[localvar0])
[004A] (5D)     if (localvar5 > ((localvar1 + localvar3) + 12)) {
[005B] (BD)       return(1)
[005E] (**)     }
[005E] (**)   }
[005E] (**) }
[005E] (BD) return(localvar4)
[0062] (66) stopObjectCodeB()
END
```

I'm pretty sure the same should be applied to `startObjectQuick` but there is explicit comment saying it shouldn't so better check it more.